name: Create release
run-name: "Creating release: ${{ inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag produced by Calibre-Web
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ inputs.tag }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/calibre-web:latest,${{ vars.DOCKERHUB_USERNAME }}/calibre-web:${{ inputs.tag }}
